name: Build LaTeX and Publish Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Ensures the action checks out all branches and tags for proper tagging

    - name: Compile LaTeX Document using Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/workdir texlive/texlive pdflatex -output-directory=build /workdir/butaslac_cv.tex

    - name: Create a new tag
      env:
        TZ: 'Asia/Tokyo'
      run: |
        TAG=$(date +v%Y%m%d-%H%M%S)
        echo "Creating tag $TAG"
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag $TAG
        git push origin $TAG
        echo "NEW_TAG=$TAG" >> $GITHUB_ENV

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/butaslac_cv.pdf
        tag_name: ${{ env.NEW_TAG }}
        name: Release ${{ env.NEW_TAG }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}