name: Build LaTeX and Publish Release

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install LaTeX
      run: sudo apt-get install texlive-full
      
    - name: Compile LaTeX Document
      run: |
        mkdir -p build
        pdflatex -output-directory=build butaslac_cv.tex
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/butaslac_cv.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
